### ISSUE TITLE
Broken link on Introduction

### ISSUE THREAD

**Issue by lucasavila00** [denoland/manual#360]
This is the broken link: https://github.com/denoland/manual/blob/main/introduction.md?plain=1#L22

```
and a
  [language server for your editor](./getting_started/setup_your_environment.md#using-an-editoride).
```

I won't submit a PR as I don't know what is the proper link, but I believe it should be the language server section? https://deno.land/manual/language_server

**Comment by bartlomieju** [comment]
Fixed in https://github.com/denoland/manual/pull/359

**Comment by lucasavila00** [comment]
@bartlomieju 

#359 did not touch the link on line 22, I believe it's still broken.
